name: GitHub Package Get

inputs:
  package-version:
    description: 'The version of the package to get'
    required: true

outputs:
  package-id:
    description: 'The id of the package'
    value: ${{ steps.get_package_id.outputs.package_id }}

runs:
  using: "composite"
  steps:
    - name: Get the previous package id for the same package version
      id: get_package_id
      run: |
        echo "::set-output name=package_id::$(gh package version list ${{ github.repository }} --package-version ${{ github.event.inputs.package-version }} --json | jq -r '.[0].id')"
