name: GitHub Package Delete

on:
  workflow_call:
    inputs:
      github-organisation:
        description: 'GitHub organisation name'
        required: true
        type: string
        default: ${{ github.repository_owner }}
      package-type:
        description: 'Package type'
        required: true
        type: string
      package-name:
        description: 'Package name to delete'
        required: true
        type: string
      package-version:
        description: 'Package version to delete'
        required: true
        type: string
    secrets:
      github-token:
        description: 'GitHub token'
        required: false

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Get package id
        id: package_id
        env:
          GH_TOKEN: ${{ secrets.github-token || github.token }}
        run: |
          package_id=$(gh api /orgs/${{ inputs.github-organisation }}/packages/${{ inputs.package-type }}/${{ inputs.package-name }} | jq '.[] | select(.name=="${{ inputs.package-version }}")')
          echo "$package_id"

          echo "id=$package_id" >> $GITHUB_OUTPUT

      - name: Delete package version
        if: steps.package_id.outputs.id != null
        env:
          GH_TOKEN: ${{ secrets.github-token || github.token }}
        run: |
          result=$(gh api -X DELETE /orgs/${{ inputs.github-organisation }}/packages/${{ inputs.package-type }}/${{ inputs.package-name }}/versions/${{ steps.package_id.outputs.id }})
          echo "$result"
